#!/bin/sh

# 型チェックを実行
echo "Running type checks..."
deno check main.ts

# 型チェックの終了コードを取得
CHECK_RESULT=$?

if [ $CHECK_RESULT -ne 0 ]; then
  echo "Type check failed. Commit aborted."
  exit 1
fi

# Denoのテストを実行
echo "Running Deno tests..."
deno test --allow-net --allow-run --unstable-kv

# テストの終了コードを取得
TEST_RESULT=$?

# テストが失敗した場合はコミットを中止
if [ $TEST_RESULT -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

echo "All checks and tests passed. Proceeding with commit."
exit 0